import {
  changeApi,
  changeParam,
  changeText,
  generateHead,
  generateInterfaceName,
  generateName,
  generatePromise,
  generateType,
  toUpperCase,
} from './index';

test('changeText', () => {
  expect(changeText('a_b')).toEqual('aB');
  expect(changeText('a_b')).toEqual('aB');
  expect(changeText('a_Bc_d')).toEqual('aBcD');
});

test('changeApi', () => {
  expect(changeApi('/api/test')).toEqual("'/api/test'");
  // eslint-disable-next-line no-template-curly-in-string
  expect(changeApi('/api/test/{id}')).toEqual('`/api/test/${params.id}`');
});

test('changeParam', () => {
  expect(changeParam('/api/test'.split('/'))).toEqual(['', 'api', 'test']);
  expect(changeParam('/api/test/{id}'.split('/'))).toEqual(['', 'api', 'test', 'id']);
  expect(changeParam('/api/test/{id}/{bb}'.split('/'))).toEqual(['', 'api', 'test', 'id', 'bb']);
});

test('generateName', () => {
  expect(generateName('/api/test')).toEqual('apiTest');
  expect(generateName('/api/test/bcd')).toEqual('testBcd');
  expect(generateName('/api/test/{id}/{px}')).toEqual('idPx');
});
test('toUpperCase', () => {
  expect(toUpperCase('jnjsa')).toEqual('Jnjsa');
  expect(toUpperCase('cjsn')).toEqual('Cjsn');
  expect(toUpperCase('_as')).toEqual('_as');
  expect(toUpperCase('1dsa')).toEqual('1dsa');
});

test('generateType', () => {
  const data = {
    type: 'array',
    items: {
      $ref: '#/definitions/PlaystationGamePrice',
    },
  };
  expect(generateType(data)).toEqual('PlaystationGamePrice []');
  const data1 = {
    type: 'string',
  };
  expect(generateType(data1)).toEqual('string');
  const data2 = {
    $ref: '#/definitions/PlaystationGamePrice',
  };
  expect(generateType(data2)).toEqual('PlaystationGamePrice');
  const data3 = {
    type: 'integer',
  };
  expect(generateType(data3)).toEqual('number');
});

test('generateHead', () => {
  const data = {
    host: 'alitajs.com',
    basePath: '/v1',
    info: {
      version: '1.0.0',
    },
  };
  expect(generateHead(data)).toEqual(`
/**
 * This file is automatically generated using Alitajs/codegen
 * Host: alitajs.com
 * BasePath: /v1
 * Version: 1.0.0
 * Description: 这个文件是使用脚本自动生成的，原则上来说，你不需要手动修改它
 * Others:
**/
import request from 'umi-request';\n
`);
});

test('generatePromise', () => {
  expect(
    generatePromise({
      $ref: '#/definitions/ResultWrapper«ListResult«PlaystationGamePrice»»',
    }),
  ).toEqual('ResultWrapperListResultPlaystationGamePrice');
  expect(generatePromise({ $ref: '#/definitions/分页数据«优惠券对象»' })).toEqual(
    'TemporaryVariable0',
  );
  expect(generatePromise({ type: 'string' })).toEqual('string');
});

test('generateInterfaceName', () => {
  expect(generateInterfaceName('分页数据«优惠券对象»')).toEqual('TemporaryVariable0');
  expect(generateInterfaceName('AnalysisData«List»')).toEqual('AnalysisDataList');
});
